export const ANSWER_POST_REQUEST='ANSWER_POST_REQUEST'
export const ANSWER_POST_SUCCESS='ANSWER_POST_SUCCESS'
export const ANSWER_POST_FAIL='ANSWER_POST_FAIL'
export const ANSWER_POST_NULL='ANSWER_POST_NULL'

export const ANSWER_UPVOTE_REQUEST = 'ANSWER_UPVOTE_REQUEST'
export const ANSWER_UPVOTE_SUCCESS='ANSWER_UPVOTE_SUCCESS'
export const ANSWER_UPVOTE_FAIL='ANSWER_UPVOTE_FAIL'
export const ANSWER_UPVOTE_NULL='ANSWER_UPVOTE_NULL'


export const ANSWER_UNUPVOTE_REQUEST = 'ANSWER_UNUPVOTE_REQUEST'
export const ANSWER_UNUPVOTE_SUCCESS='ANSWER_UNUPVOTE_SUCCESS'
export const ANSWER_UNUPVOTE_FAIL='ANSWER_UNUPVOTE_FAIL'
export const ANSWER_UNUPVOTE_NULL='ANSWER_UNUPVOTE_NULL'

export const ANSWER_DOWNVOTE_REQUEST = 'ANSWER_DOWNVOTE_REQUEST'
export const ANSWER_DOWNVOTE_SUCCESS='ANSWER_DOWNVOTE_SUCCESS'
export const ANSWER_DOWNVOTE_FAIL='ANSWER_DOWNVOTE_FAIL'
export const ANSWER_DOWNVOTE_NULL='ANSWER_DOWNVOTE_NULL'

export const ANSWER_UNDOWNVOTE_REQUEST = 'ANSWER_UNDOWNVOTE_REQUEST'
export const ANSWER_UNDOWNVOTE_SUCCESS='ANSWER_UNDOWNVOTE_SUCCESS'
export const ANSWER_UNDOWNVOTE_FAIL='ANSWER_UNDOWNVOTE_FAIL'
export const ANSWER_UNDOWNVOTE_NULL='ANSWER_UNDOWNVOTE_NULL'



export const ANSWER_EDIT_REQUEST = 'ANSWER_EDIT_REQUEST'
export const ANSWER_EDIT_SUCCESS = 'ANSWER_EDIT_SUCCESS'
export const ANSWER_EDIT_FAIL = 'ANSWER_EDIT_FAIL'
export const ANSWER_EDIT_NULL = 'ANSWER_EDIT_NULL'

export const ANSWER_DELETE_REQUEST = 'ANSWER_DELETE_REQUEST'
export const ANSWER_DELETE_SUCCESS = 'ANSWER_DELETE_SUCCESS'
export const ANSWER_DELETE_FAIL = 'ANSWER_DELETE_FAIL'

export const ANSWER_SHOW_REQUEST = 'ANSWER_SHOW_REQUEST'
export const ANSWER_SHOW_SUCCESS = 'ANSWER_SHOW_SUCCESS'
export const ANSWER_SHOW_FAIL = 'ANSWER_SHOW_FAIL'


export const ANSWER_FETCH_USER_REQUEST = 'ANSWER_FETCH_USER__REQUEST'
export const ANSWER_FETCH_USER_SUCCESS = 'ANSWER_FETCH_USER_SUCCESS'
export const ANSWER_FETCH_USER_FAIL = 'ANSWER_FETCH_USER_FAIL'
export const ANSWER_FETCH_USER_UNLOAD = 'ANSWER_FETCH_USER_UNLOAD'

export const ANSWER_COMMENT_POST_REQUEST = 'ANSWER_COMMENT_POST_REQUEST'
export const ANSWER_COMMENT_POST_SUCCESS = 'ANSWER_COMMENT_POST_SUCCESS'
export const ANSWER_COMMENT_POST_FAIL = 'ANSWER_COMMENT_POST_FAIL'
export const ANSWER_COMMENT_POST_NULL = 'ANSWER_COMMENT_POST_NULL'

export const ANSWER_COMMENT_GET_REQUEST = 'ANSWER_COMMENT_GET_REQUEST'
export const ANSWER_COMMENT_GET_SUCCESS = 'ANSWER_COMMENT_GET_SUCCESS'
export const ANSWER_COMMENT_GET_FAIL = 'ANSWER_COMMENT_GET_FAIL'


export const ANSWER_COMMENT_DELETE_REQUEST = 'ANSWER_COMMENT_DELETE_REQUEST'
export const ANSWER_COMMENT_DELETE_SUCCESS = 'ANSWER_COMMENT_DELETE_SUCCESS'
export const ANSWER_COMMENT_DELETE_FAIL = 'ANSWER_COMMENT_DELETE_FAIL'

export const ANSWER_COMMENT_LENGTH_REQUEST = 'ANSWER_COMMENT_LENGTH_REQUEST'
export const ANSWER_COMMENT_LENGTH_SUCCESS = 'ANSWER_COMMENT_LENGTH_SUCCESS'
export const ANSWER_COMMENT_LENGTH_FAIL = 'ANSWER_COMMENT_LENGTH_FAIL'
