export const ANSWER_COMMENT_POST_REQUEST = 'ANSWER_COMMENT_POST_REQUEST'
export const ANSWER_COMMENT_POST_SUCCESS = 'ANSWER_COMMENT_POST_SUCCESS'
export const ANSWER_COMMENT_POST_FAIL = 'ANSWER_COMMENT_POST_FAIL'
export const ANSWER_COMMENT_POST_NULL = 'ANSWER_COMMENT_POST_NULL'


export const ANSWER_COMMENT_DELETE_REQUEST = 'ANSWER_COMMENT_DELETE_REQUEST'
export const ANSWER_COMMENT_DELETE_SUCCESS = 'ANSWER_COMMENT_DELETE_SUCCESS'
export const ANSWER_COMMENT_DELETE_FAIL = 'ANSWER_COMMENT_DELETE_FAIL'