export const QUESTION_POST_REQUEST='QUESTION_POST_REQUEST';
export const QUESTION_POST_SUCCESS='QUESTION_POST_SUCCESS';
export const QUESTION_POST_FAIL='QUESTION_POST_FAIL';
export const QUESTION_POST_NULL='QUESTION_POST_NULL';


export const QUESTION_UPVOTE_REQUEST = 'QUESTION_UPVOTE_REQUEST'
export const QUESTION_UPVOTE_SUCCESS='QUESTION_UPVOTE_SUCCESS'
export const QUESTION_UPVOTE_FAIL='QUESTION_UPVOTE_FAIL'
export const QUESTION_UPVOTE_NULL='QUESTION_UPVOTE_NULL'


export const QUESTION_UNUPVOTE_REQUEST = 'QUESTION_UNUPVOTE_REQUEST'
export const QUESTION_UNUPVOTE_SUCCESS='QUESTION_UNUPVOTE_SUCCESS'
export const QUESTION_UNUPVOTE_FAIL='QUESTION_UNUPVOTE_FAIL'
export const QUESTION_UNUPVOTE_NULL='QUESTION_UNUPVOTE_NULL'

export const QUESTION_DOWNVOTE_REQUEST = 'QUESTION_DOWNVOTE_REQUEST'
export const QUESTION_DOWNVOTE_SUCCESS='QUESTION_DOWNVOTE_SUCCESS'
export const QUESTION_DOWNVOTE_FAIL='QUESTION_DOWNVOTE_FAIL'
export const QUESTION_DOWNVOTE_NULL='QUESTION_DOWNVOTE_NULL'

export const QUESTION_UNDOWNVOTE_REQUEST = 'QUESTION_UNDOWNVOTE_REQUEST'
export const QUESTION_UNDOWNVOTE_SUCCESS='QUESTION_UNDOWNVOTE_SUCCESS'
export const QUESTION_UNDOWNVOTE_FAIL='QUESTION_UNDOWNVOTE_FAIL'
export const QUESTION_UNDOWNVOTE_NULL='QUESTION_UNDOWNVOTE_NULL'

export const QUESTION_FETCH_USER_REQUEST='QUESTION_FETCH_USER_REQUEST';
export const QUESTION_FETCH_USER_SUCCESS='QUESTION_FETCH_USER_SUCCESS';
export const QUESTION_FETCH_USER_FAIL='QUESTION_FETCH_USER_FAIL';
export const QUESTION_FETCH_USER_UNLOAD='QUESTION_FETCH_USER_UNLOAD'

export const QUESTION_FULL_REQUEST='QUESTION_FULL_REQUEST';
export const QUESTION_FULL_SUCCESS='QUESTION_FULL_SUCCESS';
export const QUESTION_FULL_FAIL='QUESTION_FULL_FAIL';

export const QUESTION_EDIT = 'QUESTION_EDIT'
export const QUESTION_EDIT_REQUEST = 'QUESTION_EDIT_REQUEST'
export const QUESTION_EDIT_SUCCESS = 'QUESTION_EDIT_SUCCESS'
export const QUESTION_EDIT_FAIL = 'QUESTION_EDIT_FAIL'

export const QUESTION_DELETE_REQUEST = 'QUESTION_DELETE_REQUEST'
export const QUESTION_DELETE_SUCCESS = 'QUESTION_DELETE_SUCCESS'
export const QUESTION_DELETE_FAIL = 'QUESTION_DELETE_FAIL'

export const QUESTION_PAGE_REQUEST = 'QUESTION_PAGE_REQUEST'
export const QUESTION_PAGE_SUCCESS = 'QUESTION_PAGE_SUCCESS'
export const QUESTION_PAGE_FAIL = 'QUESTION_PAGE_FAIL'

export const QUESTION_REPORT_REQUEST = 'QUESTION_REPORT_REQUEST'
export const QUESTION_REPORT_SUCCESS = 'QUESTION_REPORT_SUCCESS'
export const QUESTION_REPORT_FAIL = 'QUESTION_REPORT_FAIL'
export const QUESTION_REPORT_NULL='QUESTION_REPORT_NULL';
