export const USER_LOGIN_REQUEST='USER_LOGIN_REQUEST';
export const USER_LOGIN_SUCCESS='USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL';

export const USER_LOGOUT = 'USER_LOGOUT';

export const USER_REGISTER_REQUEST='USER_REGISTER_REQUEST';
export const USER_REGISTER_SUCCESS='USER_REGISTER_SUCCESS';
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL';
export const USER_REGISTER_UNLOAD = 'USER_REGISTER_UNLOAD';

export const USER_PROFILE_REQUEST='USER_PROFILE_REQUEST';
export const USER_PROFILE_SUCCESS='USER_PROFILE_SUCCESS';
export const USER_PROFILE_FAIL = 'USER_PROFILE_FAIL';
export const USER_PROFILE_UNLOAD = 'USER_PROFILE_UNLOAD';

export const USER_EDIT_EMAIL_REQUEST='USER_EDIT_EMAIL_REQUEST';
export const USER_EDIT_EMAIL_SUCCESS='USER_EDIT_EMAIL_SUCCESS';
export const USER_EDIT_EMAIL_FAIL = 'USER_EDIT_EMAIL_FAIL';

export const USER_EDIT_USERNAME_REQUEST='USER_EDIT_USERNAME_REQUEST';
export const USER_EDIT_USERNAME_SUCCESS='USER_EDIT_USERNAME_SUCCESS';
export const USER_EDIT_USERNAME_FAIL = 'USER_EDIT_USERNAME_FAIL';


export const USER_EDIT_DESCRIPTION_REQUEST='USER_EDIT_DESCRIPTION_REQUEST';
export const USER_EDIT_DESCRIPTION_SUCCESS='USER_EDIT_DESCRIPTION_SUCCESS';
export const USER_EDIT_DESCRIPTION_FAIL = 'USER_EDIT_DESCRIPTION_FAIL';


export const USER_EDIT_PASSWORD_REQUEST='USER_EDIT_PASSWORD_REQUEST';
export const USER_EDIT_PASSWORD_SUCCESS='USER_EDIT_PASSWORD_SUCCESS';
export const USER_EDIT_PASSWORD_FAIL = 'USER_EDIT_PASSWORD_FAIL';

export const USER_EDIT_NULL = 'USER_EDIT_NULL';

export const VERIFY_EMAIL_REQUEST='VERIFY_EMAIL_REQUEST';
export const VERIFY_EMAIL_SUCCESS='VERIFY_EMAIL_SUCCESS';
export const VERIFY_EMAIL_FAIL = 'VERIFY_EMAIL_FAIL';

export const USER_DELETE_REQUEST='USER_DELETE_REQUEST';
export const USER_DELETE_SUCCESS='USER_DELETE_SUCCESS';
export const USER_DELETE_FAIL = 'USER_DELETE_FAIL';
export const USER_DELETE_UNLOAD = 'USER_DELETE_UNLOAD';

export const FETCH_USER_DETAILS_REQUEST='FETCH_USER_DETAILS_REQUEST'
export const FETCH_USER_DETAILS_SUCCESS='FETCH_USER_DETAILS_SUCCESS'
export const FETCH_USER_DETAILS_FAIL='FETCH_USER_DETAILS_FAIL'

